** Godelian awareness and the death of existensialism

Strouss says someone might say science might itself is helpless against existensialism onslaught.

Humanity is kinda in the same spot back from 1956 -> physical and non-physical form woven together.Poor and positive support is no help.

imagining yourself made yourself an ontological leap from non-physical leap to physical being that has sprouted subjectively that science can't
explain. Why this is important is -> gnostic, complete understanding of self in society,family and in terms of absolute self.

we dont have a rational philsophy which continues from where science and rational positvity drops it -> poetic existensialism is no match.

where is the rational philosophy of existensialism who can rationally explain the metaphysics of it all ?

true ethics which revelas to us in a true  rational way the true nature of the being.

is it possible to belive in them without beliveing in all edges.

we are stuck on this exitensialsm island as a an artifact of a material object -> scientifc reductionism and we dont understand ourselves fully
and because of that we don't understand the environment around us fully -> absurd objects that floats around us that panics around existensialism
and "emotional existensialism". From the position we belive in a stupid positivism -> corporate , overly smilly, contrived escapism that we dont ourselves from
that we can't seem to seperate from the self , even as we discuss existensialism.

Emotional Existensialism strives to support the ideas of the "corporate" existensialsm which boils down to the lowest common denominator of satisfying all
and then boiling them to the ideas of equality and egality which is not a natural course of action but rather a artificial view of the world created to satisfy a
point and appeal to a collective.

*** Confronting the Enemy

we simply do not attack the enemy on its own but rather contrive various methods to deflect it and makes it an aescetic approach and throwing names and accusing people not understanding the
truth without any mathematics to support their rigidity -> without the success of this materialistic phenomemon.




